name: Python checkstyle

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '**/scripts/virtual-host-gatherer'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**.py'
      - '**/scripts/virtual-host-gatherer'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/systemsmanagement/uyuni/master/docker/containers_tw/uyuni-master-python:latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

    - id: files
      uses: Ana06/get-changed-files@25f79e676e7ea1868813e21465014798211fad8c #v2.3.0
      with:
        filter: |
          *.py
          scripts/virtual-host-gatherer
    
    - name: Run black on files
      run: |
        if [[ -z "${{ steps.files.outputs.added_modified_renamed }}" ]]; then
            echo "no files to check, OK"
        else
            black --check --diff -t py36 ${{ steps.files.outputs.added_modified_renamed }}
        fi

    - name: Run pylint on files
      run: |
        if [[ -z "${{ steps.files.outputs.added_modified_renamed }}" ]]; then
            echo "no files to check, OK"
        else
            pylint --rcfile=/root/.pylintrc ${{ steps.files.outputs.added_modified_renamed }}
        fi
